### ISSUE TITLE
Regression in the 5.9.8 Release

### ISSUE THREAD

**Issue by rajatvig** [buildkite/buildkite-agent-metrics#304]
## Issue Details

Post an upgrade from 5.9.4 to 5.9.8, we noticed that the metrics for running builds are not getting updated after the builds complete. This behaviour causes a change in scaling behavior as metric calculation we use sums running and scheduled builds for a queue to decide if there are enough agents running. The metric we see the same value for is `buildkite_queues_running_jobs_count`.

## Setup

We are running unclustered agents and running the agent metrics binary to export metrics to Prometheus.

**Comment by DrJosh9000** [comment]
Hi @rajatvig , thanks for raising the issue. There was one change to the Prometheus backend (#288) which may explain the issue you're seeing - all metrics now have a `cluster` label, where previously they may not have. This could break queries if the label doesn't match or isn't [ignored](https://prometheus.io/docs/prometheus/latest/querying/operators/#vector-matching) appropriately. Unfortunately the change was necessary to fix a panic. 

Can you share the exact PromQL query?

**Comment by DrJosh9000** [comment]
I see, interesting. The metric being stuck could be related to #296, which removed a well-intended but heavy-handed gauge reset. Is the metric stuck for all queues, or a particular queue? Is it stuck for queues that were deleted?

**Comment by rajatvig** [comment]
It was stuck for queues that were deleted, i.e. no builds were running.

**Comment by DrJosh9000** [comment]
Sounds like #305 should fix it - I'll optimistically close this as fixed, please give [v5.9.9](https://github.com/buildkite/buildkite-agent-metrics/releases/tag/v5.9.9) a try and feel free to re-open if you see the same issue.

**Comment by rajatvig** [comment]
I just gave 5.9.9 a try and still seeing similar behaviour. I setup 2 jobs on the `test` queue and the metric `buildkite_queues_running_jobs_count{queue="test"}` went to 2 and then to 1 but did not go to 0 or absent like earlier.
